---
# postmoogle is an email to matrix bot
# Project source code URL: https://gitlab.com/etke.cc/postmoogle

matrix_bot_postmoogle_enabled: true

matrix_bot_postmoogle_container_image_self_build: false
matrix_bot_postmoogle_docker_repo: "https://gitlab.com/etke.cc/postmoogle.git"
matrix_bot_postmoogle_docker_repo_version: "{{ 'main' if matrix_bot_postmoogle_version == 'latest' else matrix_bot_postmoogle_version }}"
matrix_bot_postmoogle_docker_src_files_path: "{{ matrix_base_data_path }}/postmoogle/docker-src"

matrix_bot_postmoogle_version: latest
matrix_bot_postmoogle_docker_image: "{{ matrix_bot_postmoogle_docker_image_name_prefix }}postmoogle:{{ matrix_bot_postmoogle_version }}"
matrix_bot_postmoogle_docker_image_name_prefix: "{{ 'localhost/' if matrix_bot_postmoogle_container_image_self_build else 'registry.gitlab.com/etke.cc/' }}"
matrix_bot_postmoogle_docker_image_force_pull: "{{ matrix_bot_postmoogle_docker_image.endswith(':latest') }}"

matrix_bot_postmoogle_base_path: "{{ matrix_base_data_path }}/postmoogle"
matrix_bot_postmoogle_config_path: "{{ matrix_bot_postmoogle_base_path }}/config"
matrix_bot_postmoogle_data_path: "{{ matrix_bot_postmoogle_base_path }}/data"

# A list of extra arguments to pass to the container
matrix_bot_postmoogle_container_extra_arguments: []

# List of systemd services that matrix-bot-postmoogle.service depends on
matrix_bot_postmoogle_systemd_required_services_list: ['docker.service']

# List of systemd services that matrix-bot-postmoogle.service wants
matrix_bot_postmoogle_systemd_wanted_services_list: []


# Database-related configuration fields.
#
# To use SQLite, stick to these defaults.
#
# To use Postgres:
# - change the engine (`matrix_bot_postmoogle_database_engine: 'postgres'`)
# - adjust your database credentials via the `matrix_bot_postmoogle_database_*` variables
matrix_bot_postmoogle_database_engine: 'sqlite'

matrix_bot_postmoogle_sqlite_database_path_local: "{{ matrix_bot_postmoogle_data_path }}/bot.db"
matrix_bot_postmoogle_sqlite_database_path_in_container: "/data/bot.db"

matrix_bot_postmoogle_database_username: 'postmoogle'
matrix_bot_postmoogle_database_password: 'some-password'
matrix_bot_postmoogle_database_hostname: 'matrix-postgres'
matrix_bot_postmoogle_database_port: 5432
matrix_bot_postmoogle_database_name: 'postmoogle'

matrix_bot_postmoogle_database_connection_string: 'postgres://{{ matrix_bot_postmoogle_database_username }}:{{ matrix_bot_postmoogle_database_password }}@{{ matrix_bot_postmoogle_database_hostname }}:{{ matrix_bot_postmoogle_database_port }}/{{ matrix_bot_postmoogle_database_name }}?sslmode=disable'

matrix_bot_postmoogle_storage_database: "{{
	{
		'sqlite': matrix_bot_postmoogle_sqlite_database_path_in_container,
		'postgres': matrix_bot_postmoogle_database_connection_string,
	}[matrix_bot_postmoogle_database_engine]
}}"

matrix_bot_postmoogle_database_dialect: "{{
  {
    'sqlite': 'sqlite3',
    'postgres': 'postgres',
  }[matrix_bot_postmoogle_database_engine]
}}"


# The bot's username. This user needs to be created manually beforehand.
# Also see `matrix_bot_postmoogle_password`.
matrix_bot_postmoogle_login: "postmoogle"

# The password that the bot uses to authenticate.
matrix_bot_postmoogle_password: ''

matrix_bot_postmoogle_homeserver: "{{ matrix_homeserver_container_url }}"

# Command prefix
matrix_bot_postmoogle_prefix: '!pm'

# Max email size in megabytes, including attachments
matrix_bot_postmoogle_maxsize: '1024'

# Allow room settings changes by any room participant
matrix_bot_postmoogle_noowner: false

# Allow Postmoogle use by users over federation
matrix_bot_postmoogle_federation: false

# Sentry DSN
matrix_bot_postmoogle_sentry: ''

# Log level
matrix_bot_postmoogle_loglevel: 'INFO'

# Disable encryption
matrix_bot_postmoogle_noencryption: false

matrix_bot_postmoogle_domain: "{{ matrix_server_fqn_matrix }}"

# in-container port
matrix_bot_postmoogle_port: '2525'

# on-host port
matrix_bot_postmoogle_smtp_host_bind_port: '25'

# Additional environment variables to pass to the postmoogle container
#
# Example:
# matrix_bot_postmoogle_environment_variables_extension: |
#   postmoogle_TEXT_DONE=Done
matrix_bot_postmoogle_environment_variables_extension: ''
